// Compiles a synthetic consumer that imports every runtime export subpath of
// the just-built package. Under Node16 module resolution that type-checks
// against the sibling .d.ts artifacts emitted at exactly the locations
// advertised by publishConfig.exports, proving the generated types are real
// and consumable rather than merely present on disk.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { findBin, spawnFileSync, stageFail } from './run.mjs';

function collectTargets(node, conditionPath, results) {
  if (typeof node === 'string') {
    results.push({ condition: conditionPath.join(' > '), value: node });
    return;
  }
  if (node && typeof node === 'object') {
    for (const [key, value] of Object.entries(node)) {
      collectTargets(value, [...conditionPath, key], results);
    }
  }
}

function relativeImport(fromDir, targetAbs) {
  const rel = path.relative(fromDir, targetAbs).replaceAll(path.sep, '/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

export function ensureGeneratedTypes(pkgDir) {
  const pkg = JSON.parse(
    readFileSync(path.join(pkgDir, 'package.json'), 'utf8'),
  );
  const exportMap = pkg.publishConfig?.exports;
  if (!exportMap) {
    stageFail(
      'typegen-check',
      `${pkg.name} has no publishConfig.exports; cannot validate published types.`,
    );
  }

  const groups = [];
  for (const [subpath, node] of Object.entries(exportMap)) {
    const entries = [];
    collectTargets(node, [subpath], entries);
    groups.push({ subpath, entries });
  }

  const runtimeImports = [];
  for (const { subpath, entries } of groups.filter(
    (group) => group.subpath !== './package.json',
  )) {
    for (const entry of entries.filter((candidate) =>
      candidate.condition.includes('types'),
    )) {
      const dtsAbs = path.resolve(pkgDir, entry.value);
      if (!existsSync(dtsAbs)) {
        stageFail(
          'typegen-check',
          `${pkg.name} advertises types ${entry.value} (${subpath}) but it is missing.`,
        );
      }
      if (!dtsAbs.endsWith('.d.ts')) {
        stageFail(
          'typegen-check',
          `${pkg.name} types condition ${subpath} points to non-.d.ts: ${entry.value}`,
        );
      }
      if (statSync(dtsAbs).size === 0) {
        stageFail(
          'typegen-check',
          `${pkg.name} generated types file is empty: ${entry.value}`,
        );
      }
    }

    const runtime =
      entries.find(
        (entry) =>
          !entry.condition.includes('types') && entry.value.endsWith('.js'),
      ) ?? entries.find((entry) => !entry.condition.includes('types'));
    if (!runtime) {
      stageFail(
        'typegen-check',
        `${pkg.name} export ${subpath} has no runtime target for consumer verification.`,
      );
    }
    const runtimeAbs = path.resolve(pkgDir, runtime.value);
    if (!existsSync(runtimeAbs) || statSync(runtimeAbs).size === 0) {
      stageFail(
        'typegen-check',
        `${pkg.name} export ${subpath} runtime artifact missing or empty: ${runtime.value}`,
      );
    }
    runtimeImports.push({ subpath, value: runtime.value });
  }

  if (runtimeImports.length === 0) {
    stageFail(
      'typegen-check',
      `${pkg.name} publishes no runtime subpaths; nothing to verify.`,
    );
  }

  const outDir = path.join(pkgDir, '.verify-typegen');
  rmSync(outDir, { recursive: true, force: true });
  const srcDir = path.join(outDir, 'src');
  mkdirSync(srcDir, { recursive: true });

  const lines = runtimeImports.map((entry, index) => {
    const imp = relativeImport(srcDir, path.resolve(pkgDir, entry.value));
    return [
      `// export ${entry.subpath} -> ${entry.value}`,
      `import * as api${index} from ${JSON.stringify(imp)};`,
      `void api${index};`,
    ].join('\n');
  });
  writeFileSync(
    path.join(srcDir, 'consumer.ts'),
    `// Synthetic package consumer generated by tools/verify/typegen-check.mjs\n${lines.join('\n')}\n`,
  );
  writeFileSync(
    path.join(outDir, 'tsconfig.json'),
    `${JSON.stringify(
      {
        compilerOptions: {
          noEmit: true,
          strict: true,
          skipLibCheck: false,
          noErrorTruncation: true,
          target: 'ES2022',
          module: 'Node16',
          moduleResolution: 'Node16',
          lib: ['ES2022'],
        },
        include: ['src/**/*.ts'],
      },
      null,
      2,
    )}\n`,
  );

  const tsc = findBin(pkgDir, 'tsc');
  try {
    spawnFileSync(tsc, ['-p', path.join(outDir, 'tsconfig.json')], pkgDir, {
      stage: 'typegen-check (tsc)',
    });
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
  console.log(
    `[typegen-check] ${pkg.name}: ${runtimeImports.length} export subpath(s) compile against generated d.ts`,
  );
}
